(() => {
  if (!(location.hostname.endsWith("github.io") || location.protocol === "file:")) return;
  document.querySelector(".automation-panel").hidden = true;
  document.querySelector(".owner-label").lastChild.textContent = " Painel demonstrativo";
  document.querySelector(".agenda-head p").textContent = "Reservas e configuracoes salvas neste navegador para a demonstracao.";
  const statuses = { aguardando_pix: "Aguardando PIX", pendente: "Pendente", confirmado: "Confirmado", concluido: "Concluido", falta: "Falta", cancelado: "Cancelado" };
  const weekdays = ["Domingo", "Segunda-feira", "Terca-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sabado"];
  const money = (value) => (value / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
  const serviceForm = document.querySelector("#service-form");

  function resetService() { serviceForm.reset(); document.querySelector("#service-id").value = ""; }
  function populateAgendaFilters() {
    const statusField = document.querySelector("#agenda-status"), serviceField = document.querySelector("#agenda-service"), selectedStatus = statusField.value, selectedService = serviceField.value;
    statusField.innerHTML = `<option value="">Todos</option>${Object.entries(statuses).map(([value, label]) => `<option value="${value}">${label}</option>`).join("")}`;
    serviceField.innerHTML = `<option value="">Todos</option>${DemoStore.getAllServices().map((item) => `<option value="${item.id}">${item.name}</option>`).join("")}`;
    statusField.value = selectedStatus; serviceField.value = selectedService;
  }
  function renderServices() {
    const list = DemoStore.getAllServices();
    document.querySelector("#service-table").innerHTML = list.length ? list.map((item) => `<div class="service-row"><div><b>${item.name}</b><small>${item.duration} min · ${item.price.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })} · ${item.active ? "Ativo" : "Pausado"}</small></div><button type="button" data-edit="${item.id}">Editar</button><button type="button" data-toggle="${item.id}">${item.active ? "Pausar" : "Ativar"}</button><button type="button" data-delete="${item.id}">Excluir</button></div>`).join("") : "<p>Nenhum servico cadastrado.</p>";
  }
  function renderSchedule() {
    const schedule = DemoStore.getSchedule();
    document.querySelector("#schedule-form").innerHTML = weekdays.map((day, index) => { const raw = schedule[index], hours = Array.isArray(raw) ? { open: raw[0], close: raw[1] } : raw; return `<div class="schedule-row"><input id="day-${index}" type="checkbox" ${hours ? "checked" : ""}/><label for="day-${index}">${day}</label><input id="open-${index}" type="time" value="${hours?.open || "09:00"}" ${hours ? "" : "disabled"}/><input id="close-${index}" type="time" value="${hours?.close || "18:00"}" ${hours ? "" : "disabled"}/><input id="break-start-${index}" type="time" value="${hours?.breakStart || ""}" ${hours ? "" : "disabled"}/><input id="break-end-${index}" type="time" value="${hours?.breakEnd || ""}" ${hours ? "" : "disabled"}/></div>`; }).join("");
    const exceptions = schedule.overrides || {}; document.querySelector("#exception-list").innerHTML = Object.entries(exceptions).sort().map(([date, item]) => `<div><span>${date.split("-").reverse().join("/")} · ${item.closed ? "Fechado" : `${item.open} - ${item.close}`}</span><button type="button" data-remove-exception="${date}">Remover</button></div>`).join("") || "<small>Nenhuma data especial.</small>";
  }
  function renderBookings() {
    const bookings = DemoStore.getBookings(), active = bookings.filter((item) => !["concluido", "falta", "cancelado"].includes(item.status));
    const date = document.querySelector("#agenda-date").value, status = document.querySelector("#agenda-status").value, customer = document.querySelector("#agenda-customer").value.trim().toLocaleLowerCase("pt-BR"), serviceId = document.querySelector("#agenda-service").value;
    const filtered = bookings.filter((item) => (!date || item.date === date) && (!status || item.status === status) && (!customer || item.name.toLocaleLowerCase("pt-BR").includes(customer)) && (!serviceId || item.serviceId === serviceId));
    document.querySelector("#stats").innerHTML = `<article><span>Reservas</span><strong>${bookings.length}</strong></article><article><span>Aguardando sinal</span><strong>${bookings.filter((item) => item.status === "aguardando_pix").length}</strong></article><article><span>Confirmados</span><strong>${bookings.filter((item) => item.status === "confirmado").length}</strong></article><article><span>Agenda ativa</span><strong>${active.length}</strong></article>`;
    const table = document.querySelector("#booking-table"); document.querySelector("#agenda-result").textContent = `${filtered.length} de ${bookings.length} reserva(s) encontrada(s).`;
    table.innerHTML = filtered.length ? `<div class="table-head"><span>Cliente</span><span>Servico</span><span>Horario</span><span>Status</span><span>Acao</span></div>${filtered.map((item) => `<div class="booking-row"><div><b>${item.name}</b><small>${item.phone}<br/>${item.code}</small></div><span>${item.service}</span><span>${item.date}<br/><b>${item.time}</b></span><span class="status ${item.status}">${statuses[item.status]}</span><div class="payment-action"><select data-booking="${item.code}">${Object.entries(statuses).map(([value, label]) => `<option value="${value}" ${value === item.status ? "selected" : ""}>${label}</option>`).join("")}</select>${item.payment_status === "aguardando" ? `<button type="button" data-payment="${item.code}">Confirmar PIX ${money(item.payment_amount)}</button>` : ""}</div></div>`).join("")}` : `<div class="empty-state"><h3>Nenhuma reserva encontrada.</h3><p>Ajuste ou limpe os filtros para consultar a agenda.</p></div>`;
  }
  function renderReports() {
    const start = document.querySelector("#report-start").value, end = document.querySelector("#report-end").value;
    const bookings = DemoStore.getBookings().filter((item) => (!start || item.date >= start) && (!end || item.date <= end));
    const services = DemoStore.getAllServices(), priceOf = (item) => item.price ?? services.find((service) => service.id === item.serviceId)?.price ?? 0;
    const completed = bookings.filter((item) => ["confirmado", "concluido"].includes(item.status));
    const projected = completed.reduce((total, item) => total + priceOf(item), 0);
    const deposits = bookings.filter((item) => item.payment_status === "pago").reduce((total, item) => total + (item.payment_amount || 0), 0);
    const absences = bookings.filter((item) => item.status === "falta").length, cancellations = bookings.filter((item) => item.status === "cancelado").length;
    document.querySelector("#report-stats").innerHTML = `<article><span>Reservas no periodo</span><strong>${bookings.length}</strong></article><article><span>Faturamento previsto</span><strong>${projected.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong></article><article><span>Sinais confirmados</span><strong>${money(deposits)}</strong></article><article><span>Faltas</span><strong>${absences}</strong></article><article><span>Cancelamentos</span><strong>${cancellations}</strong></article>`;
    const grouped = bookings.reduce((all, item) => ({ ...all, [item.service]: (all[item.service] || 0) + 1 }), {}), entries = Object.entries(grouped).sort((left, right) => right[1] - left[1]), maximum = entries[0]?.[1] || 1;
    document.querySelector("#service-report").innerHTML = entries.length ? entries.map(([name, quantity]) => `<div class="report-row"><span>${name}</span><div class="report-track"><div class="report-fill" style="width:${(quantity / maximum) * 100}%"></div></div><b>${quantity}</b></div>`).join("") : "<p class=loading>Nenhuma reserva no periodo.</p>";
    const favorite = entries[0]?.[0] || "Nenhum servico";
    document.querySelector("#report-insight").innerHTML = bookings.length ? `<b>${favorite}</b> e o servico mais procurado neste periodo. ${completed.length} reserva(s) ja estao confirmadas ou concluidas.` : "Selecione outro periodo ou crie uma reserva na pagina publica para ver os indicadores.";
  }
  function renderReminders() {
    const now = Date.now(), limit = now + 24 * 60 * 60 * 1000;
    const upcoming = DemoStore.getBookings().filter((item) => { const when = new Date(`${item.date}T${item.time}:00`).getTime(); return when >= now && when <= limit && ["aguardando_pix", "pendente", "confirmado"].includes(item.status); }).sort((left, right) => `${left.date}${left.time}`.localeCompare(`${right.date}${right.time}`));
    document.querySelector("#reminder-list").innerHTML = upcoming.length ? upcoming.map((item) => `<article><div><b>${item.name}</b><span>${item.service} · ${item.date.split("-").reverse().join("/")} as ${item.time}</span></div><button type="button" data-reminder="${item.code}">${item.reminder_sent_at ? "Reenviar lembrete" : "Simular envio"}</button></article>`).join("") : "<p>Nenhum lembrete para as proximas 24 horas.</p>";
  }
  serviceForm.addEventListener("submit", (event) => {
    event.preventDefault(); const id = document.querySelector("#service-id").value, services = DemoStore.getAllServices(), item = { id: id || `servico-${Date.now()}`, name: document.querySelector("#service-name").value.trim(), description: document.querySelector("#service-description").value.trim(), duration: Number(document.querySelector("#service-duration").value), price: Number(document.querySelector("#service-price").value), active: true };
    if (!item.name || !item.description || !Number.isFinite(item.duration) || !Number.isFinite(item.price)) return;
    const index = services.findIndex((service) => service.id === id); if (index >= 0) item.active = services[index].active, services[index] = item; else services.push(item); DemoStore.saveServices(services); resetService(); renderServices(); populateAgendaFilters();
  });
  document.querySelector("#service-clear").addEventListener("click", resetService);
  document.querySelector("#service-table").addEventListener("click", (event) => {
    const id = event.target.dataset.edit || event.target.dataset.toggle || event.target.dataset.delete; if (!id) return; const services = DemoStore.getAllServices(), item = services.find((service) => service.id === id); if (event.target.dataset.edit) { document.querySelector("#service-id").value = item.id; document.querySelector("#service-name").value = item.name; document.querySelector("#service-description").value = item.description || ""; document.querySelector("#service-duration").value = item.duration; document.querySelector("#service-price").value = item.price; } else if (event.target.dataset.delete) { if (!window.confirm(`Excluir o servico ${item.name}?`)) return; DemoStore.saveServices(services.filter((service) => service.id !== id)); renderServices(); populateAgendaFilters(); } else { item.active = !item.active; DemoStore.saveServices(services); renderServices(); }
  });
  document.querySelector("#schedule-form").addEventListener("change", (event) => { const id = event.target.id?.match(/^day-(\d)$/); if (!id) return; const enabled = event.target.checked; ["open", "close", "break-start", "break-end"].forEach((field) => { document.querySelector(`#${field}-${id[1]}`).disabled = !enabled; }); });
  document.querySelector("#schedule-form").addEventListener("submit", (event) => { event.preventDefault(); const previous = DemoStore.getSchedule(), schedule = { overrides: previous.overrides || {} }; for (let index = 0; index < 7; index += 1) { const enabled = document.querySelector(`#day-${index}`).checked, open = document.querySelector(`#open-${index}`).value, close = document.querySelector(`#close-${index}`).value, breakStart = document.querySelector(`#break-start-${index}`).value, breakEnd = document.querySelector(`#break-end-${index}`).value; if (enabled && (open >= close || (Boolean(breakStart) !== Boolean(breakEnd)) || (breakStart && (breakStart >= breakEnd || breakStart < open || breakEnd > close)))) { document.querySelector("#schedule-feedback").textContent = `Confira horario e pausa de ${weekdays[index]}.`; return; } schedule[index] = enabled ? { open, close, breakStart, breakEnd } : null; } DemoStore.saveSchedule(schedule); document.querySelector("#schedule-feedback").textContent = "Agenda salva para a demonstracao online."; renderSchedule(); });
  document.querySelector("#exception-form").addEventListener("submit", (event) => { event.preventDefault(); const date = document.querySelector("#exception-date").value, mode = document.querySelector("#exception-mode").value, open = document.querySelector("#exception-open").value, close = document.querySelector("#exception-close").value; if (!date || (mode === "open" && open >= close)) return; const schedule = DemoStore.getSchedule(); schedule.overrides = schedule.overrides || {}; schedule.overrides[date] = mode === "closed" ? { closed: true } : { open, close, breakStart: "", breakEnd: "" }; DemoStore.saveSchedule(schedule); event.currentTarget.reset(); renderSchedule(); });
  document.querySelector("#exception-list").addEventListener("click", (event) => { const date = event.target.dataset.removeException; if (!date) return; const schedule = DemoStore.getSchedule(); delete schedule.overrides[date]; DemoStore.saveSchedule(schedule); renderSchedule(); });
  document.querySelector("#agenda-filter").addEventListener("input", renderBookings);
  document.querySelector("#clear-agenda-filter").addEventListener("click", () => { document.querySelector("#agenda-filter").reset(); renderBookings(); });
  document.querySelector("#booking-table").addEventListener("change", (event) => { if (!event.target.dataset.booking) return; DemoStore.updateBooking(event.target.dataset.booking, { status: event.target.value }); renderBookings(); renderReports(); renderReminders(); });
  document.querySelector("#booking-table").addEventListener("click", (event) => { const code = event.target.dataset.payment; if (!code) return; DemoStore.updateBooking(code, { status: "confirmado", payment_status: "pago" }); renderBookings(); renderReports(); renderReminders(); });
  document.querySelector("#reminder-list").addEventListener("click", (event) => { const code = event.target.dataset.reminder; if (!code) return; const booking = DemoStore.getBookings().find((item) => item.code === code), message = encodeURIComponent(`Ola, ${booking.name}! Lembrando do seu horario na Barbearia Norte: ${booking.date.split("-").reverse().join("/")} as ${booking.time}. Ate breve!`); DemoStore.updateBooking(code, { reminder_sent_at: new Date().toISOString() }); window.open(`https://wa.me/${booking.phone.replace(/\D/g, "")}?text=${message}`, "_blank", "noopener"); renderReminders(); });
  document.querySelector("#report-filter").addEventListener("submit", (event) => { event.preventDefault(); renderReports(); });
  const today = new Date(), monthStart = new Date(today.getFullYear(), today.getMonth(), 1), monthEnd = new Date(today.getFullYear(), today.getMonth() + 1, 0); document.querySelector("#report-start").value = monthStart.toISOString().slice(0, 10); document.querySelector("#report-end").value = monthEnd.toISOString().slice(0, 10);
  populateAgendaFilters(); renderServices(); renderSchedule(); renderBookings(); renderReminders(); renderReports(); lucide.createIcons();
})();
